using Ingres.Client;
using MetroFramework;
using MetroFramework.Controls;
using System;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using WindowsFormsApplication3.proyectoDataSetTableAdapters;

namespace WindowsFormsApplication3
{
    partial class Empleado
    {
        private System.Data.DataTable dt;

        private System.Windows.Forms.BindingSource bs = new System.Windows.Forms.BindingSource();

        private IContainer components = null;

        private MetroTextBox id;

        private MetroTextBox prinom;

        private MetroButton Create;

        private new MetroButton Update;

        private MetroButton Delete;

        private MetroLabel metroLabel1;

        private MetroLabel metroLabel2;

        private proyectoDataSet proyectoDataSet;

        private System.Windows.Forms.BindingSource readrolBindingSource;

        private read_rolTableAdapter read_rolTableAdapter;

        private MetroGrid metroGrid1;

        private MetroLabel seg_nom;

        private MetroTextBox senom;

        private MetroLabel pri_ape;

        private MetroTextBox priape;

        private MetroLabel seg_ape;

        private MetroTextBox seape;

        private MetroLabel calle;

        private MetroTextBox ca;

        private MetroLabel metroLabel4;

        private MetroTextBox departamento;

        private MetroLabel metroLabel5;

        private MetroTextBox ciudad;

        private MetroLabel metroLabel6;

        private MetroTextBox numcasa;

        private MetroLabel metroLabel7;

        private MetroTextBox avenida;

        private MetroLabel metroLabel3;

        private MetroTextBox referencia;

        private MetroLabel metroLabel8;

        private MetroTextBox pricorreo;

        private MetroLabel metroLabel9;

        private MetroTextBox secorreo;

        private MetroLabel metroLabel10;

        private MetroLabel metroLabel11;

        private MetroDateTime metroDateTime1;

        private MetroDateTime metroDateTime2;

        private MetroLabel metroLabel12;

        private void InitializeComponent()
        {
            this.components = new Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.id = new MetroTextBox();
            this.prinom = new MetroTextBox();
            this.Create = new MetroButton();
            this.Update = new MetroButton();
            this.Delete = new MetroButton();
            this.metroLabel1 = new MetroLabel();
            this.metroLabel2 = new MetroLabel();
            this.readrolBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.proyectoDataSet = new proyectoDataSet();
            this.read_rolTableAdapter = new read_rolTableAdapter();
            this.metroGrid1 = new MetroGrid();
            this.seg_nom = new MetroLabel();
            this.senom = new MetroTextBox();
            this.pri_ape = new MetroLabel();
            this.priape = new MetroTextBox();
            this.seg_ape = new MetroLabel();
            this.seape = new MetroTextBox();
            this.calle = new MetroLabel();
            this.ca = new MetroTextBox();
            this.metroLabel4 = new MetroLabel();
            this.departamento = new MetroTextBox();
            this.metroLabel5 = new MetroLabel();
            this.ciudad = new MetroTextBox();
            this.metroLabel6 = new MetroLabel();
            this.numcasa = new MetroTextBox();
            this.metroLabel7 = new MetroLabel();
            this.avenida = new MetroTextBox();
            this.metroLabel3 = new MetroLabel();
            this.referencia = new MetroTextBox();
            this.metroLabel8 = new MetroLabel();
            this.pricorreo = new MetroTextBox();
            this.metroLabel9 = new MetroLabel();
            this.secorreo = new MetroTextBox();
            this.metroLabel10 = new MetroLabel();
            this.metroLabel11 = new MetroLabel();
            this.metroDateTime1 = new MetroDateTime();
            this.metroDateTime2 = new MetroDateTime();
            this.metroLabel12 = new MetroLabel();
            ((ISupportInitialize)this.readrolBindingSource).BeginInit();
            ((ISupportInitialize)this.proyectoDataSet).BeginInit();
            ((ISupportInitialize)this.metroGrid1).BeginInit();
            base.SuspendLayout();
            this.id.CustomButton.Image = null;
            this.id.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.id.CustomButton.Name = "";
            this.id.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.id.CustomButton.Style = MetroColorStyle.Blue;
            this.id.CustomButton.TabIndex = 1;
            this.id.CustomButton.Theme = MetroThemeStyle.Light;
            this.id.CustomButton.UseSelectable = true;
            this.id.CustomButton.Visible = false;
            this.id.Lines = new string[0];
            this.id.Location = new System.Drawing.Point(127, 51);
            this.id.MaxLength = 32767;
            this.id.Name = "id";
            this.id.PasswordChar = '\0';
            this.id.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.id.SelectedText = "";
            this.id.SelectionLength = 0;
            this.id.SelectionStart = 0;
            this.id.ShortcutsEnabled = true;
            this.id.Size = new System.Drawing.Size(131, 23);
            this.id.Style = MetroColorStyle.Blue;
            this.id.TabIndex = 8;
            this.id.Theme = MetroThemeStyle.Light;
            this.id.UseSelectable = true;
            this.id.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.id.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.prinom.CustomButton.Image = null;
            this.prinom.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.prinom.CustomButton.Name = "";
            this.prinom.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.prinom.CustomButton.Style = MetroColorStyle.Blue;
            this.prinom.CustomButton.TabIndex = 1;
            this.prinom.CustomButton.Theme = MetroThemeStyle.Light;
            this.prinom.CustomButton.UseSelectable = true;
            this.prinom.CustomButton.Visible = false;
            this.prinom.Lines = new string[0];
            this.prinom.Location = new System.Drawing.Point(127, 80);
            this.prinom.MaxLength = 32767;
            this.prinom.Name = "prinom";
            this.prinom.PasswordChar = '\0';
            this.prinom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.prinom.SelectedText = "";
            this.prinom.SelectionLength = 0;
            this.prinom.SelectionStart = 0;
            this.prinom.ShortcutsEnabled = true;
            this.prinom.Size = new System.Drawing.Size(131, 23);
            this.prinom.Style = MetroColorStyle.Blue;
            this.prinom.TabIndex = 9;
            this.prinom.Theme = MetroThemeStyle.Light;
            this.prinom.UseSelectable = true;
            this.prinom.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.prinom.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.Create.Location = new System.Drawing.Point(321, 212);
            this.Create.Name = "Create";
            this.Create.Size = new System.Drawing.Size(75, 23);
            this.Create.Style = MetroColorStyle.Blue;
            this.Create.TabIndex = 10;
            this.Create.Text = "Create";
            this.Create.Theme = MetroThemeStyle.Light;
            this.Create.UseSelectable = true;
            this.Create.Click += new EventHandler(this.metroButton1_Click);
            this.Update.Location = new System.Drawing.Point(440, 212);
            this.Update.Name = "Update";
            this.Update.Size = new System.Drawing.Size(75, 23);
            this.Update.Style = MetroColorStyle.Blue;
            this.Update.TabIndex = 11;
            this.Update.Text = "Update";
            this.Update.Theme = MetroThemeStyle.Light;
            this.Update.UseSelectable = true;
            this.Update.Click += new EventHandler(this.Update_Click);
            this.Delete.Location = new System.Drawing.Point(561, 212);
            this.Delete.Name = "Delete";
            this.Delete.Size = new System.Drawing.Size(75, 23);
            this.Delete.Style = MetroColorStyle.Orange;
            this.Delete.TabIndex = 12;
            this.Delete.Text = "Delete";
            this.Delete.Theme = MetroThemeStyle.Light;
            this.Delete.UseSelectable = true;
            this.Delete.Click += new EventHandler(this.Delete_Click);
            this.metroLabel1.AutoSize = true;
            this.metroLabel1.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel1.ForeColor = System.Drawing.Color.White;
            this.metroLabel1.Location = new System.Drawing.Point(37, 51);
            this.metroLabel1.Name = "metroLabel1";
            this.metroLabel1.Size = new System.Drawing.Size(84, 19);
            this.metroLabel1.Style = MetroColorStyle.Blue;
            this.metroLabel1.TabIndex = 13;
            this.metroLabel1.Text = "Id Empleado";
            this.metroLabel1.Theme = MetroThemeStyle.Light;
            this.metroLabel1.UseCustomBackColor = true;
            this.metroLabel1.UseCustomForeColor = true;
            this.metroLabel1.Click += new EventHandler(this.metroLabel1_Click);
            this.metroLabel2.AutoSize = true;
            this.metroLabel2.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel2.ForeColor = System.Drawing.Color.White;
            this.metroLabel2.Location = new System.Drawing.Point(18, 80);
            this.metroLabel2.Name = "metroLabel2";
            this.metroLabel2.Size = new System.Drawing.Size(103, 19);
            this.metroLabel2.Style = MetroColorStyle.Teal;
            this.metroLabel2.TabIndex = 14;
            this.metroLabel2.Text = "Primer Nombre";
            this.metroLabel2.Theme = MetroThemeStyle.Light;
            this.metroLabel2.UseCustomBackColor = true;
            this.metroLabel2.UseCustomForeColor = true;
            this.metroLabel2.Click += new EventHandler(this.metroLabel2_Click);
            this.readrolBindingSource.DataMember = "read_rol";
            this.readrolBindingSource.DataSource = this.proyectoDataSet;
            this.proyectoDataSet.DataSetName = "proyectoDataSet";
            this.proyectoDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.read_rolTableAdapter.ClearBeforeFill = true;
            this.metroGrid1.AllowUserToResizeRows = false;
            this.metroGrid1.BackgroundColor = System.Drawing.Color.FromArgb(255, 255, 255);
            this.metroGrid1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.metroGrid1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.metroGrid1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle.BackColor = System.Drawing.Color.FromArgb(0, 177, 89);
            dataGridViewCellStyle.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255);
            dataGridViewCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(0, 208, 104);
            dataGridViewCellStyle.SelectionForeColor = System.Drawing.Color.FromArgb(17, 17, 17);
            dataGridViewCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.metroGrid1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
            this.metroGrid1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(136, 136, 136);
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(0, 208, 104);
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(17, 17, 17);
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.metroGrid1.DefaultCellStyle = dataGridViewCellStyle2;
            this.metroGrid1.EnableHeadersVisualStyles = false;
            this.metroGrid1.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.metroGrid1.GridColor = System.Drawing.Color.FromArgb(255, 255, 255);
            this.metroGrid1.Location = new System.Drawing.Point(37, 258);
            this.metroGrid1.Name = "metroGrid1";
            this.metroGrid1.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(0, 177, 89);
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI", 11f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255);
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(0, 208, 104);
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(17, 17, 17);
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.metroGrid1.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
            this.metroGrid1.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.metroGrid1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.metroGrid1.Size = new System.Drawing.Size(908, 232);
            this.metroGrid1.Style = MetroColorStyle.Green;
            this.metroGrid1.TabIndex = 15;
            this.seg_nom.AutoSize = true;
            this.seg_nom.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.seg_nom.ForeColor = System.Drawing.Color.White;
            this.seg_nom.Location = new System.Drawing.Point(6, 109);
            this.seg_nom.Name = "seg_nom";
            this.seg_nom.Size = new System.Drawing.Size(115, 19);
            this.seg_nom.Style = MetroColorStyle.Teal;
            this.seg_nom.TabIndex = 17;
            this.seg_nom.Text = "Segundo Nombre";
            this.seg_nom.Theme = MetroThemeStyle.Light;
            this.seg_nom.UseCustomBackColor = true;
            this.seg_nom.UseCustomForeColor = true;
            this.senom.CustomButton.Image = null;
            this.senom.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.senom.CustomButton.Name = "";
            this.senom.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.senom.CustomButton.Style = MetroColorStyle.Blue;
            this.senom.CustomButton.TabIndex = 1;
            this.senom.CustomButton.Theme = MetroThemeStyle.Light;
            this.senom.CustomButton.UseSelectable = true;
            this.senom.CustomButton.Visible = false;
            this.senom.Lines = new string[0];
            this.senom.Location = new System.Drawing.Point(127, 109);
            this.senom.MaxLength = 32767;
            this.senom.Name = "senom";
            this.senom.PasswordChar = '\0';
            this.senom.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.senom.SelectedText = "";
            this.senom.SelectionLength = 0;
            this.senom.SelectionStart = 0;
            this.senom.ShortcutsEnabled = true;
            this.senom.Size = new System.Drawing.Size(131, 23);
            this.senom.Style = MetroColorStyle.Blue;
            this.senom.TabIndex = 16;
            this.senom.Theme = MetroThemeStyle.Light;
            this.senom.UseSelectable = true;
            this.senom.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.senom.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.pri_ape.AutoSize = true;
            this.pri_ape.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.pri_ape.ForeColor = System.Drawing.Color.White;
            this.pri_ape.Location = new System.Drawing.Point(18, 138);
            this.pri_ape.Name = "pri_ape";
            this.pri_ape.Size = new System.Drawing.Size(102, 19);
            this.pri_ape.Style = MetroColorStyle.Teal;
            this.pri_ape.TabIndex = 19;
            this.pri_ape.Text = "Primer Apellido";
            this.pri_ape.Theme = MetroThemeStyle.Light;
            this.pri_ape.UseCustomBackColor = true;
            this.pri_ape.UseCustomForeColor = true;
            this.priape.CustomButton.Image = null;
            this.priape.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.priape.CustomButton.Name = "";
            this.priape.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.priape.CustomButton.Style = MetroColorStyle.Blue;
            this.priape.CustomButton.TabIndex = 1;
            this.priape.CustomButton.Theme = MetroThemeStyle.Light;
            this.priape.CustomButton.UseSelectable = true;
            this.priape.CustomButton.Visible = false;
            this.priape.Lines = new string[0];
            this.priape.Location = new System.Drawing.Point(127, 138);
            this.priape.MaxLength = 32767;
            this.priape.Name = "priape";
            this.priape.PasswordChar = '\0';
            this.priape.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.priape.SelectedText = "";
            this.priape.SelectionLength = 0;
            this.priape.SelectionStart = 0;
            this.priape.ShortcutsEnabled = true;
            this.priape.Size = new System.Drawing.Size(131, 23);
            this.priape.Style = MetroColorStyle.Blue;
            this.priape.TabIndex = 18;
            this.priape.Theme = MetroThemeStyle.Light;
            this.priape.UseSelectable = true;
            this.priape.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.priape.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.seg_ape.AutoSize = true;
            this.seg_ape.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.seg_ape.ForeColor = System.Drawing.Color.White;
            this.seg_ape.Location = new System.Drawing.Point(7, 167);
            this.seg_ape.Name = "seg_ape";
            this.seg_ape.Size = new System.Drawing.Size(114, 19);
            this.seg_ape.Style = MetroColorStyle.Teal;
            this.seg_ape.TabIndex = 21;
            this.seg_ape.Text = "Segundo Apellido";
            this.seg_ape.Theme = MetroThemeStyle.Light;
            this.seg_ape.UseCustomBackColor = true;
            this.seg_ape.UseCustomForeColor = true;
            this.seape.CustomButton.Image = null;
            this.seape.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.seape.CustomButton.Name = "";
            this.seape.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.seape.CustomButton.Style = MetroColorStyle.Blue;
            this.seape.CustomButton.TabIndex = 1;
            this.seape.CustomButton.Theme = MetroThemeStyle.Light;
            this.seape.CustomButton.UseSelectable = true;
            this.seape.CustomButton.Visible = false;
            this.seape.Lines = new string[0];
            this.seape.Location = new System.Drawing.Point(127, 167);
            this.seape.MaxLength = 32767;
            this.seape.Name = "seape";
            this.seape.PasswordChar = '\0';
            this.seape.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.seape.SelectedText = "";
            this.seape.SelectionLength = 0;
            this.seape.SelectionStart = 0;
            this.seape.ShortcutsEnabled = true;
            this.seape.Size = new System.Drawing.Size(131, 23);
            this.seape.Style = MetroColorStyle.Blue;
            this.seape.TabIndex = 20;
            this.seape.Theme = MetroThemeStyle.Light;
            this.seape.UseSelectable = true;
            this.seape.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.seape.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.calle.AutoSize = true;
            this.calle.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.calle.ForeColor = System.Drawing.Color.White;
            this.calle.Location = new System.Drawing.Point(396, 51);
            this.calle.Name = "calle";
            this.calle.Size = new System.Drawing.Size(38, 19);
            this.calle.Style = MetroColorStyle.Teal;
            this.calle.TabIndex = 23;
            this.calle.Text = "Calle";
            this.calle.Theme = MetroThemeStyle.Light;
            this.calle.UseCustomBackColor = true;
            this.calle.UseCustomForeColor = true;
            this.ca.CustomButton.Image = null;
            this.ca.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.ca.CustomButton.Name = "";
            this.ca.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.ca.CustomButton.Style = MetroColorStyle.Blue;
            this.ca.CustomButton.TabIndex = 1;
            this.ca.CustomButton.Theme = MetroThemeStyle.Light;
            this.ca.CustomButton.UseSelectable = true;
            this.ca.CustomButton.Visible = false;
            this.ca.Lines = new string[0];
            this.ca.Location = new System.Drawing.Point(440, 51);
            this.ca.MaxLength = 32767;
            this.ca.Name = "ca";
            this.ca.PasswordChar = '\0';
            this.ca.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ca.SelectedText = "";
            this.ca.SelectionLength = 0;
            this.ca.SelectionStart = 0;
            this.ca.ShortcutsEnabled = true;
            this.ca.Size = new System.Drawing.Size(131, 23);
            this.ca.Style = MetroColorStyle.Blue;
            this.ca.TabIndex = 22;
            this.ca.Theme = MetroThemeStyle.Light;
            this.ca.UseSelectable = true;
            this.ca.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.ca.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel4.AutoSize = true;
            this.metroLabel4.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel4.ForeColor = System.Drawing.Color.White;
            this.metroLabel4.Location = new System.Drawing.Point(340, 167);
            this.metroLabel4.Name = "metroLabel4";
            this.metroLabel4.Size = new System.Drawing.Size(94, 19);
            this.metroLabel4.Style = MetroColorStyle.Teal;
            this.metroLabel4.TabIndex = 27;
            this.metroLabel4.Text = "Departamento";
            this.metroLabel4.Theme = MetroThemeStyle.Light;
            this.metroLabel4.UseCustomBackColor = true;
            this.metroLabel4.UseCustomForeColor = true;
            this.departamento.CustomButton.Image = null;
            this.departamento.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.departamento.CustomButton.Name = "";
            this.departamento.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.departamento.CustomButton.Style = MetroColorStyle.Blue;
            this.departamento.CustomButton.TabIndex = 1;
            this.departamento.CustomButton.Theme = MetroThemeStyle.Light;
            this.departamento.CustomButton.UseSelectable = true;
            this.departamento.CustomButton.Visible = false;
            this.departamento.Lines = new string[0];
            this.departamento.Location = new System.Drawing.Point(440, 167);
            this.departamento.MaxLength = 32767;
            this.departamento.Name = "departamento";
            this.departamento.PasswordChar = '\0';
            this.departamento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.departamento.SelectedText = "";
            this.departamento.SelectionLength = 0;
            this.departamento.SelectionStart = 0;
            this.departamento.ShortcutsEnabled = true;
            this.departamento.Size = new System.Drawing.Size(131, 23);
            this.departamento.Style = MetroColorStyle.Blue;
            this.departamento.TabIndex = 26;
            this.departamento.Theme = MetroThemeStyle.Light;
            this.departamento.UseSelectable = true;
            this.departamento.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.departamento.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel5.AutoSize = true;
            this.metroLabel5.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel5.ForeColor = System.Drawing.Color.White;
            this.metroLabel5.Location = new System.Drawing.Point(383, 138);
            this.metroLabel5.Name = "metroLabel5";
            this.metroLabel5.Size = new System.Drawing.Size(51, 19);
            this.metroLabel5.Style = MetroColorStyle.Teal;
            this.metroLabel5.TabIndex = 29;
            this.metroLabel5.Text = "Ciudad";
            this.metroLabel5.Theme = MetroThemeStyle.Light;
            this.metroLabel5.UseCustomBackColor = true;
            this.metroLabel5.UseCustomForeColor = true;
            this.ciudad.CustomButton.Image = null;
            this.ciudad.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.ciudad.CustomButton.Name = "";
            this.ciudad.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.ciudad.CustomButton.Style = MetroColorStyle.Blue;
            this.ciudad.CustomButton.TabIndex = 1;
            this.ciudad.CustomButton.Theme = MetroThemeStyle.Light;
            this.ciudad.CustomButton.UseSelectable = true;
            this.ciudad.CustomButton.Visible = false;
            this.ciudad.Lines = new string[0];
            this.ciudad.Location = new System.Drawing.Point(440, 138);
            this.ciudad.MaxLength = 32767;
            this.ciudad.Name = "ciudad";
            this.ciudad.PasswordChar = '\0';
            this.ciudad.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ciudad.SelectedText = "";
            this.ciudad.SelectionLength = 0;
            this.ciudad.SelectionStart = 0;
            this.ciudad.ShortcutsEnabled = true;
            this.ciudad.Size = new System.Drawing.Size(131, 23);
            this.ciudad.Style = MetroColorStyle.Blue;
            this.ciudad.TabIndex = 28;
            this.ciudad.Theme = MetroThemeStyle.Light;
            this.ciudad.UseSelectable = true;
            this.ciudad.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.ciudad.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel6.AutoSize = true;
            this.metroLabel6.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel6.ForeColor = System.Drawing.Color.White;
            this.metroLabel6.Location = new System.Drawing.Point(361, 109);
            this.metroLabel6.Name = "metroLabel6";
            this.metroLabel6.Size = new System.Drawing.Size(73, 19);
            this.metroLabel6.Style = MetroColorStyle.Teal;
            this.metroLabel6.TabIndex = 31;
            this.metroLabel6.Text = "Num. Casa";
            this.metroLabel6.Theme = MetroThemeStyle.Light;
            this.metroLabel6.UseCustomBackColor = true;
            this.metroLabel6.UseCustomForeColor = true;
            this.numcasa.CustomButton.Image = null;
            this.numcasa.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.numcasa.CustomButton.Name = "";
            this.numcasa.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.numcasa.CustomButton.Style = MetroColorStyle.Blue;
            this.numcasa.CustomButton.TabIndex = 1;
            this.numcasa.CustomButton.Theme = MetroThemeStyle.Light;
            this.numcasa.CustomButton.UseSelectable = true;
            this.numcasa.CustomButton.Visible = false;
            this.numcasa.Lines = new string[0];
            this.numcasa.Location = new System.Drawing.Point(440, 109);
            this.numcasa.MaxLength = 32767;
            this.numcasa.Name = "numcasa";
            this.numcasa.PasswordChar = '\0';
            this.numcasa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numcasa.SelectedText = "";
            this.numcasa.SelectionLength = 0;
            this.numcasa.SelectionStart = 0;
            this.numcasa.ShortcutsEnabled = true;
            this.numcasa.Size = new System.Drawing.Size(131, 23);
            this.numcasa.Style = MetroColorStyle.Blue;
            this.numcasa.TabIndex = 30;
            this.numcasa.Theme = MetroThemeStyle.Light;
            this.numcasa.UseSelectable = true;
            this.numcasa.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.numcasa.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel7.AutoSize = true;
            this.metroLabel7.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel7.ForeColor = System.Drawing.Color.White;
            this.metroLabel7.Location = new System.Drawing.Point(378, 80);
            this.metroLabel7.Name = "metroLabel7";
            this.metroLabel7.Size = new System.Drawing.Size(56, 19);
            this.metroLabel7.Style = MetroColorStyle.Teal;
            this.metroLabel7.TabIndex = 33;
            this.metroLabel7.Text = "Avenida";
            this.metroLabel7.Theme = MetroThemeStyle.Light;
            this.metroLabel7.UseCustomBackColor = true;
            this.metroLabel7.UseCustomForeColor = true;
            this.avenida.CustomButton.Image = null;
            this.avenida.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.avenida.CustomButton.Name = "";
            this.avenida.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.avenida.CustomButton.Style = MetroColorStyle.Blue;
            this.avenida.CustomButton.TabIndex = 1;
            this.avenida.CustomButton.Theme = MetroThemeStyle.Light;
            this.avenida.CustomButton.UseSelectable = true;
            this.avenida.CustomButton.Visible = false;
            this.avenida.Lines = new string[0];
            this.avenida.Location = new System.Drawing.Point(440, 80);
            this.avenida.MaxLength = 32767;
            this.avenida.Name = "avenida";
            this.avenida.PasswordChar = '\0';
            this.avenida.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.avenida.SelectedText = "";
            this.avenida.SelectionLength = 0;
            this.avenida.SelectionStart = 0;
            this.avenida.ShortcutsEnabled = true;
            this.avenida.Size = new System.Drawing.Size(131, 23);
            this.avenida.Style = MetroColorStyle.Blue;
            this.avenida.TabIndex = 32;
            this.avenida.Theme = MetroThemeStyle.Light;
            this.avenida.UseSelectable = true;
            this.avenida.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.avenida.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel3.AutoSize = true;
            this.metroLabel3.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel3.ForeColor = System.Drawing.Color.White;
            this.metroLabel3.Location = new System.Drawing.Point(685, 51);
            this.metroLabel3.Name = "metroLabel3";
            this.metroLabel3.Size = new System.Drawing.Size(70, 19);
            this.metroLabel3.Style = MetroColorStyle.Teal;
            this.metroLabel3.TabIndex = 35;
            this.metroLabel3.Text = "Referencia";
            this.metroLabel3.Theme = MetroThemeStyle.Light;
            this.metroLabel3.UseCustomBackColor = true;
            this.metroLabel3.UseCustomForeColor = true;
            this.referencia.CustomButton.Image = null;
            this.referencia.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.referencia.CustomButton.Name = "";
            this.referencia.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.referencia.CustomButton.Style = MetroColorStyle.Blue;
            this.referencia.CustomButton.TabIndex = 1;
            this.referencia.CustomButton.Theme = MetroThemeStyle.Light;
            this.referencia.CustomButton.UseSelectable = true;
            this.referencia.CustomButton.Visible = false;
            this.referencia.Lines = new string[0];
            this.referencia.Location = new System.Drawing.Point(761, 51);
            this.referencia.MaxLength = 32767;
            this.referencia.Name = "referencia";
            this.referencia.PasswordChar = '\0';
            this.referencia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.referencia.SelectedText = "";
            this.referencia.SelectionLength = 0;
            this.referencia.SelectionStart = 0;
            this.referencia.ShortcutsEnabled = true;
            this.referencia.Size = new System.Drawing.Size(131, 23);
            this.referencia.Style = MetroColorStyle.Blue;
            this.referencia.TabIndex = 34;
            this.referencia.Theme = MetroThemeStyle.Light;
            this.referencia.UseSelectable = true;
            this.referencia.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.referencia.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel8.AutoSize = true;
            this.metroLabel8.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel8.ForeColor = System.Drawing.Color.White;
            this.metroLabel8.Location = new System.Drawing.Point(649, 80);
            this.metroLabel8.Name = "metroLabel8";
            this.metroLabel8.Size = new System.Drawing.Size(106, 19);
            this.metroLabel8.Style = MetroColorStyle.Teal;
            this.metroLabel8.TabIndex = 37;
            this.metroLabel8.Text = "Correo Primario";
            this.metroLabel8.Theme = MetroThemeStyle.Light;
            this.metroLabel8.UseCustomBackColor = true;
            this.metroLabel8.UseCustomForeColor = true;
            this.pricorreo.CustomButton.Image = null;
            this.pricorreo.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.pricorreo.CustomButton.Name = "";
            this.pricorreo.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.pricorreo.CustomButton.Style = MetroColorStyle.Blue;
            this.pricorreo.CustomButton.TabIndex = 1;
            this.pricorreo.CustomButton.Theme = MetroThemeStyle.Light;
            this.pricorreo.CustomButton.UseSelectable = true;
            this.pricorreo.CustomButton.Visible = false;
            this.pricorreo.Lines = new string[0];
            this.pricorreo.Location = new System.Drawing.Point(761, 80);
            this.pricorreo.MaxLength = 32767;
            this.pricorreo.Name = "pricorreo";
            this.pricorreo.PasswordChar = '\0';
            this.pricorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.pricorreo.SelectedText = "";
            this.pricorreo.SelectionLength = 0;
            this.pricorreo.SelectionStart = 0;
            this.pricorreo.ShortcutsEnabled = true;
            this.pricorreo.Size = new System.Drawing.Size(131, 23);
            this.pricorreo.Style = MetroColorStyle.Blue;
            this.pricorreo.TabIndex = 36;
            this.pricorreo.Theme = MetroThemeStyle.Light;
            this.pricorreo.UseSelectable = true;
            this.pricorreo.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.pricorreo.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel9.AutoSize = true;
            this.metroLabel9.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel9.ForeColor = System.Drawing.Color.White;
            this.metroLabel9.Location = new System.Drawing.Point(635, 109);
            this.metroLabel9.Name = "metroLabel9";
            this.metroLabel9.Size = new System.Drawing.Size(120, 19);
            this.metroLabel9.Style = MetroColorStyle.Teal;
            this.metroLabel9.TabIndex = 39;
            this.metroLabel9.Text = "Correo Secundario";
            this.metroLabel9.Theme = MetroThemeStyle.Light;
            this.metroLabel9.UseCustomBackColor = true;
            this.metroLabel9.UseCustomForeColor = true;
            this.secorreo.CustomButton.Image = null;
            this.secorreo.CustomButton.Location = new System.Drawing.Point(109, 1);
            this.secorreo.CustomButton.Name = "";
            this.secorreo.CustomButton.Size = new System.Drawing.Size(21, 21);
            this.secorreo.CustomButton.Style = MetroColorStyle.Blue;
            this.secorreo.CustomButton.TabIndex = 1;
            this.secorreo.CustomButton.Theme = MetroThemeStyle.Light;
            this.secorreo.CustomButton.UseSelectable = true;
            this.secorreo.CustomButton.Visible = false;
            this.secorreo.Lines = new string[0];
            this.secorreo.Location = new System.Drawing.Point(761, 109);
            this.secorreo.MaxLength = 32767;
            this.secorreo.Name = "secorreo";
            this.secorreo.PasswordChar = '\0';
            this.secorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.secorreo.SelectedText = "";
            this.secorreo.SelectionLength = 0;
            this.secorreo.SelectionStart = 0;
            this.secorreo.ShortcutsEnabled = true;
            this.secorreo.Size = new System.Drawing.Size(131, 23);
            this.secorreo.Style = MetroColorStyle.Blue;
            this.secorreo.TabIndex = 38;
            this.secorreo.Theme = MetroThemeStyle.Light;
            this.secorreo.UseSelectable = true;
            this.secorreo.WaterMarkColor = System.Drawing.Color.FromArgb(109, 109, 109);
            this.secorreo.WaterMarkFont = new System.Drawing.Font("Segoe UI", 12f, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Pixel);
            this.metroLabel10.AutoSize = true;
            this.metroLabel10.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel10.ForeColor = System.Drawing.Color.White;
            this.metroLabel10.Location = new System.Drawing.Point(659, 173);
            this.metroLabel10.Name = "metroLabel10";
            this.metroLabel10.Size = new System.Drawing.Size(96, 19);
            this.metroLabel10.Style = MetroColorStyle.Teal;
            this.metroLabel10.TabIndex = 42;
            this.metroLabel10.Text = "Fecha de Inicio";
            this.metroLabel10.Theme = MetroThemeStyle.Light;
            this.metroLabel10.UseCustomBackColor = true;
            this.metroLabel10.UseCustomForeColor = true;
            this.metroLabel11.AutoSize = true;
            this.metroLabel11.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel11.ForeColor = System.Drawing.Color.White;
            this.metroLabel11.Location = new System.Drawing.Point(622, 138);
            this.metroLabel11.Name = "metroLabel11";
            this.metroLabel11.Size = new System.Drawing.Size(133, 19);
            this.metroLabel11.Style = MetroColorStyle.Teal;
            this.metroLabel11.TabIndex = 43;
            this.metroLabel11.Text = "Fecha de Nacimiento";
            this.metroLabel11.Theme = MetroThemeStyle.Light;
            this.metroLabel11.UseCustomBackColor = true;
            this.metroLabel11.UseCustomForeColor = true;
            this.metroDateTime1.Location = new System.Drawing.Point(761, 138);
            this.metroDateTime1.MinimumSize = new System.Drawing.Size(0, 29);
            this.metroDateTime1.Name = "metroDateTime1";
            this.metroDateTime1.Size = new System.Drawing.Size(200, 29);
            this.metroDateTime1.TabIndex = 46;
            this.metroDateTime2.Location = new System.Drawing.Point(761, 173);
            this.metroDateTime2.MinimumSize = new System.Drawing.Size(0, 29);
            this.metroDateTime2.Name = "metroDateTime2";
            this.metroDateTime2.Size = new System.Drawing.Size(200, 29);
            this.metroDateTime2.TabIndex = 47;
            this.metroLabel12.AutoSize = true;
            this.metroLabel12.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            this.metroLabel12.FontSize = MetroLabelSize.Tall;
            this.metroLabel12.FontWeight = MetroLabelWeight.Regular;
            this.metroLabel12.ForeColor = System.Drawing.Color.White;
            this.metroLabel12.Location = new System.Drawing.Point(37, 9);
            this.metroLabel12.Name = "metroLabel12";
            this.metroLabel12.Size = new System.Drawing.Size(174, 25);
            this.metroLabel12.Style = MetroColorStyle.Blue;
            this.metroLabel12.TabIndex = 48;
            this.metroLabel12.Text = "Empleados Afiliados";
            this.metroLabel12.Theme = MetroThemeStyle.Light;
            this.metroLabel12.UseCustomBackColor = true;
            this.metroLabel12.UseCustomForeColor = true;
            base.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(0, 163, 0);
            base.ClientSize = new System.Drawing.Size(990, 508);
            base.Controls.Add(this.metroLabel12);
            base.Controls.Add(this.metroDateTime2);
            base.Controls.Add(this.metroDateTime1);
            base.Controls.Add(this.metroLabel11);
            base.Controls.Add(this.metroLabel10);
            base.Controls.Add(this.metroLabel9);
            base.Controls.Add(this.secorreo);
            base.Controls.Add(this.metroLabel8);
            base.Controls.Add(this.pricorreo);
            base.Controls.Add(this.metroLabel3);
            base.Controls.Add(this.referencia);
            base.Controls.Add(this.metroLabel7);
            base.Controls.Add(this.avenida);
            base.Controls.Add(this.metroLabel6);
            base.Controls.Add(this.numcasa);
            base.Controls.Add(this.metroLabel5);
            base.Controls.Add(this.ciudad);
            base.Controls.Add(this.metroLabel4);
            base.Controls.Add(this.departamento);
            base.Controls.Add(this.calle);
            base.Controls.Add(this.ca);
            base.Controls.Add(this.seg_ape);
            base.Controls.Add(this.seape);
            base.Controls.Add(this.pri_ape);
            base.Controls.Add(this.priape);
            base.Controls.Add(this.seg_nom);
            base.Controls.Add(this.senom);
            base.Controls.Add(this.metroGrid1);
            base.Controls.Add(this.metroLabel2);
            base.Controls.Add(this.metroLabel1);
            base.Controls.Add(this.Delete);
            base.Controls.Add(this.Update);
            base.Controls.Add(this.Create);
            base.Controls.Add(this.prinom);
            base.Controls.Add(this.id);
            this.ForeColor = System.Drawing.Color.Black;
            base.Name = "Empleado";
            this.Text = "Form1";
            base.Load += new EventHandler(this.Rol_Load);
            ((ISupportInitialize)this.readrolBindingSource).EndInit();
            ((ISupportInitialize)this.proyectoDataSet).EndInit();
            ((ISupportInitialize)this.metroGrid1).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}